#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Bhanuchander Udhayakumar

# Short bio or description (displayed in the header)
description: Wireless | RF System Design | Optical Network Systems Engineer | Pc Gamer                                

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /icons/square_icon_rsd.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: bhanuchander210@gmail.com
  facebook: bhanuchander
  flickr:
  github: Bhanuchander210
  instagram:
  linkedin: bhanuchanderu
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: Bhanuchander_U
  stackoverflow: users/8331235/bhanuchander-u # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: UC2JbRYaC-USnGgzEi2uiaqQ
  kaggle: bhanuchanderu
  reddit: Bhanuchander_U
  medium: bhanuchander210
  quora: Bhanuchander-Udhayakumar


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: bhanuchander

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-100320544-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://bhanuchander210.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

postpath: posts

defaults:
  -
    scope:
      path: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "master_navs/about"
    values:
      layout: "page"
  -
    scope:
      path: "master_navs/GitHubPages"
    values:
      layout: "gh_default"
  -
    scope:
      path: "master_navs/myapps"
    values:
      layout: "gh_default"
  -
    scope:
      path: "master_navs/eSports"
    values:
      layout: "gh_default"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME